import { Geist, Geist_Mono } from "next/font/google"; // Import Google fonts
import "./globals.css"; // Import global CSS

const geistSans = Geist({
  variable: "--font-geist-sans", // Define CSS variable for Geist Sans font
  subsets: ["latin"], // Include Latin subset
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono", // Define CSS variable for Geist Mono font
  subsets: ["latin"], // Include Latin subset
});

export const metadata = {
  title: "Create Next App", // Metadata title
  description: "Generated by create next app", // Metadata description
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} // Apply fonts and antialiasing
      >
        {children} {/* Render children components */}
      </body>
    </html>
  );
}
